title: "Mohammad Amin Ansari"
description: "EEG · Machine Learning · Signal Processing"
url: "https://MohammadAminAnsari.github.io"   # your site URL
theme: jekyll-theme-cayman                     # simple built-in theme
markdown: kramdown
